app_file_manager/urls.py
from django.urls import path, re_path
# from file_manager.folder import views
from app_file_manager import views

app_name = 'app_file_manager'


urlpatterns = [
    # folder
    path('folder/add/', views.FolderCreateView.as_view(), name='old_folder_add'),
    path('folder/', views.FolderListView.as_view(), name='old_folder_list'),
    re_path(r'^folder/delete/(?P<folder_name>[\w|\W]+)/$', views.folder_delete, name='folder_delete'),
    re_path(r'^folder/update/(?P<folder_name>[\w|\W]+)/$', views.folder_update, name='folder_update'),
    re_path(r'^folder/link/(?P<folder_name>[\w|\W]+)/$', views.folder_link, name='folder_link'),
    # re_path(r'^move/(?P<folder_name>[\w|\W]+)/$', views.folder_move, name='folder_move'),
    path('folder/add_folder/', views.folder_add_view, name='folder_add'),
    path('folder/test/', views.test_view, name='test'),



    # file
    path('file/add/', views.FileCreateView.as_view(), name='old_file_add'),
    path('file/list/', views.FileListView.as_view(), name='old_file_list'),
    path('file/<int:pk>/download/', views.FileDownloadView.as_view(), name='download'),
    re_path(r'^file/delete/(?P<file_name>[\w|\W]+)/$', views.file_delete, name='file_delete'),
    re_path(r'^file/update/(?P<file_name>[\w|\W]+)/$', views.file_update, name='file_update'),
    re_path(r'^file/link/(?P<file_name>[\w|\W]+)/$', views.file_link, name='file_link'),
    re_path(r'^file/download/(?P<file_name>[\w|\W]+)/$', views.FileDownloadNewView.as_view(), name='file_download'),
    re_path(r'^file/move/(?P<file_name>[\w|\W]+)/$', views.file_and_folder_move, name='file_move'),
    path('file/upload/', views.file_upload_view, name='file_upload'),


]

app_root/urls.py
from django.urls import path, re_path

from app_root import views
from app_smart_attendance.views import SchoolDetailView, register_school_admin_view, ProfileDetailView

app_name = 'app_root'

urlpatterns = [

    # Base URLs
    path('', views.HomePageView.as_view(), name='home'),

    path('dashboard/', views.dashboard_view, name='dashboard_view'),
    path('profile/<slug:profile_id>', ProfileDetailView.as_view(), name='profile_view'),

    path('organisation/create/', views.school_create_view, name='school_create'),
    path('organisation/<slug:school_id>/', SchoolDetailView.as_view(), name='school_detail'),
    path('organisation/<slug:school_id>/update/', views.school_update_view, name='school_update'),

    path('organisation_list/', views.organisation_list_view, name='school_list'),

    path('geolocation/create/', views.geolocation_create_view, name='geolocation_create'),

    path('register_school_admin/<slug:school_id>', register_school_admin_view, name='register_school_admin_view'),


    path('ajax/validate_username/', views.validate_username_view_ajax, name='validate_username'),
    path('ajax/validate_email/', views.validate_email_view_ajax, name='validate_email'),
    # not in use - # working - change_password_v1
    path('ajax/pass-change/', views.password_change_ajax_view, name='pass-change'),

    # path('terms-conditions/', views.TermsConditionsView.as_view(), name='terms'),

    # Contact Us URLs
    # path('contact-us/', views.contact_us_view, name='contact-us'),
    # path('query-mail-sent/', views.contact_us_success_view, name='query-mail-sent'),

    # Account Activation URLs
    # path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
    #         name='activate'),
    # path('account-activated/', views.AccountActivatedView.as_view(), name='account-activated'),

    # Sitemap URL
    # path('sitemap/', views.SiteMap.as_view(), name='sitemap'),
    # path('faq/', views.faq_page_view, name='faq'),

    # check if user is alive
    # path('is_alive', views.is_alive, name='is_alive'),

]

luein_smart_attendance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import notifications.urls
from app_root import views as root_views
from app_smart_attendance import views as app_smart_attendance_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_root.urls', namespace='root')),
    path('app/', include('app_smart_attendance.urls', namespace='app_smart_attendance')),

    # Captcha URL
    path('captcha/', include('captcha.urls'), name='captcha-image'),


    # Auth URLs
    path('login/', root_views.custom_login_view, name='login'),
    path('logout/', root_views.logout_view, name='logout'),

    # FACE RECOG APIS
    path('api/', include('api_face_recog.urls', namespace='face_recog')),


    # file manager
    path('file_manager/', include('app_file_manager.urls', namespace='app_file_manager')),

    # notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # pwa
    path('', include('pwa.urls')),

    # django-webpush
    path(r'webpush/', include('webpush.urls')),

    path('ajax/search/', app_smart_attendance_views.fetch_usernames_view_ajax, name='search'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

templates/app_file_manager/app_folder/html/add.html
{% extends 'base_file_manager.html' %}

{% load widget_tweaks %}

{% block css %}{% endblock %}

{% block content %}
<div class="ml40 mt40">
  <h4 class="text-muted mb30">Create New Folder</h4>
  <form method="post" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

{% block js %}
<script>

</script>
{% endblock %}

templates/app_file_manager/app_folder/html/partial_folder_add.html
{% load static %}

<!--Modal header-->
<div class="luein-modal-header">
    <div class="luein-modal-header-text">
        Add Folder
    </div>
    <span class="luein-modal-close">&times;</span>
</div>

<!--Modal body-->
<div class="luein-modal-body" id="luein-modal-body">
    <form method="post" action="{% url 'app_file_manager:folder_add' %}?parent={{parent_name}}" class="js_folder_add_form" id="folder_crud_form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="ma p10 w100">
            {% include 'app_file_manager/app_folder/html/partial_folder_form.html' %}
        </div>
    </form>
</div>
<!--Modal footer-->
<div class="luein-modal-footer">
    <button type="submit" class="luein-modal-button submit" form="folder_crud_form">Add</button>
    <button class="luein-modal-button cancel">Cancel</button>
</div>
<script>{% include 'app_file_manager/app_folder/js/folder_list_submit.js' %}</script>
<script src="{% static 'luein_modal/luein-modal-close.js' %}"></script>

templates/app_file_manager/app_folder/html/partial_folder_delete.html
<form method="post" action="{% url 'app_file_manager:folder_delete' folder.folder_name %}?parent={{folder.parent_name}}" class="js_folder_delete_form" id="folder_crud_form" enctype="multipart/form-data">
    {% csrf_token %}
    <p class="">Are you sure you want to Delete this folder <strong>{{ folder.folder_name }}</strong> ?</p>
</form>

templates/app_file_manager/app_folder/html/partial_folder_form.html
{% if form.non_field_errors %}
<div class="flx non_field_errors">
    <div class="non_field_errors_div">
        {{ form.non_field_errors }}
    </div>
</div>
{% endif %}

<div class="flx partitioned_form">
    <div class="form-left">
        <div class="partitioned_form_field">
            {{ form.old_name.label_tag }}
            {{ form.old_name }}
            {% if form.old_name.errors %}
            <span class="errorspan">{{ form.old_name.errors }}</span>
            {% endif %}
        </div>

        <div class="partitioned_form_field">
            {{ form.new_name.label_tag }}
            {{ form.new_name }}
            {% if form.new_name.errors %}
            <span class="errorspan">{{ form.new_name.errors }}</span>
            {% endif %}
        </div>


        <!--add folder start-->
        <div class="partitioned_form_field">
            {{ form.folder_name.label_tag }}
            {{ form.folder_name }}
            {% if form.folder_name.errors %}
            <span class="errorspan">{{ form.folder_name.errors }}</span>
            {% endif %}
        </div>

        {% if form.all_possible_root %}
        <div class="partitioned_form_field">
        {% if form.all_possible_root in form.visible_fields %}
            {{ form.all_possible_root.label_tag }}
        {% endif %}
            {{ form.all_possible_root }}
            {% if form.all_possible_root.errors %}
            <span class="errorspan">{{ form.all_possible_root.errors }}</span>
            {% endif %}
        </div>
        {% endif %}
        <!--add folder end-->


    </div>
    <div class="form-right">


    </div>

</div>

templates/app_file_manager/app_folder/html/partial_folder_link.html
<div class="flx partitioned_form w100">
    <div class="partitioned_form_field w100">
        <input type="text" name="full_link" maxlength="50" autocomplete="off" value="{{ request.build_absolute_uri }}" readonly="" required="" id="id_full_link">
    </div>
</div>

templates/app_file_manager/app_folder/html/partial_folder_update.html
{% load static %}

<!--Modal header-->
<div class="luein-modal-header">
    <div class="luein-modal-header-text">
        Update Folder Name
    </div>
    <span class="luein-modal-close">&times;</span>
</div>

<!--Modal body-->
<div class="luein-modal-body" id="luein-modal-body">
    <form method="post" action="{% url 'app_file_manager:folder_update' folder %}?parent={{parent_name}}" class="js_folder_update_form" id="folder_crud_form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="ma p10 w100">
            {% include 'app_file_manager/app_folder/html/partial_folder_form.html' %}
        </div>
    </form>
</div>
<!--Modal footer-->
<div class="luein-modal-footer">
    <button type="submit" class="luein-modal-button submit" form="folder_crud_form">Update</button>
    <button class="luein-modal-button cancel">Cancel</button>
</div>
<script>{% include 'app_file_manager/app_folder/js/folder_list_submit.js' %}</script>
<script src="{% static 'luein_modal/luein-modal-close.js' %}"></script>