app_root/urls.py
from django.urls import path, re_path

from app_root import views
from app_smart_attendance.views import SchoolDetailView, register_school_admin_view, ProfileDetailView

app_name = 'app_root'

urlpatterns = [

    # Base URLs
    path('', views.HomePageView.as_view(), name='home'),

    path('dashboard/', views.dashboard_view, name='dashboard_view'),
    path('profile/<slug:profile_id>', ProfileDetailView.as_view(), name='profile_view'),

    path('organisation/create/', views.school_create_view, name='school_create'),
    path('organisation/<slug:school_id>/', SchoolDetailView.as_view(), name='school_detail'),
    path('organisation/<slug:school_id>/update/', views.school_update_view, name='school_update'),

    path('organisation_list/', views.organisation_list_view, name='school_list'),

    path('geolocation/create/', views.geolocation_create_view, name='geolocation_create'),

    path('register_school_admin/<slug:school_id>', register_school_admin_view, name='register_school_admin_view'),


    path('ajax/validate_username/', views.validate_username_view_ajax, name='validate_username'),
    path('ajax/validate_email/', views.validate_email_view_ajax, name='validate_email'),
    # not in use - # working - change_password_v1
    path('ajax/pass-change/', views.password_change_ajax_view, name='pass-change'),

    # path('terms-conditions/', views.TermsConditionsView.as_view(), name='terms'),

    # Contact Us URLs
    # path('contact-us/', views.contact_us_view, name='contact-us'),
    # path('query-mail-sent/', views.contact_us_success_view, name='query-mail-sent'),

    # Account Activation URLs
    # path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
    #         name='activate'),
    # path('account-activated/', views.AccountActivatedView.as_view(), name='account-activated'),

    # Sitemap URL
    # path('sitemap/', views.SiteMap.as_view(), name='sitemap'),
    # path('faq/', views.faq_page_view, name='faq'),

    # check if user is alive
    # path('is_alive', views.is_alive, name='is_alive'),

]

app_smart_attendance/urls.py
from django.urls import path

from . import views

app_name = 'app_smart_attendance'

urlpatterns = [
    # template view

    path('registration/', views.student_register_view, name='student_register'),
    path('student/', views.students_view, name='students'),
    path('student/<slug:profile_id>/', views.StudentsDetailView.as_view(), name='students_detail'),

    path('mark_attendance/', views.take_attendance_view, name='take_attendance'),
    path('attendance/', views.attendance_view, name='attendance'),

    path('timesheet/overview/', views.timesheet_custom_view, name='timesheet_view'),
    path('timesheet/overview/<slug:date_text>/', views.timesheet_custom_view, name='timesheet_custom_view'),
    path('timesheet/overview/<slug:date_text>/<slug:date_range_type>/', views.timesheet_custom_view,
         name='timesheet_custom_all_view'),

    path('timesheet/overview-self/', views.timesheet_self_view, name='timesheet_self_view'),
    path('timesheet/overview-self/<slug:date_text>/', views.timesheet_self_view, name='timesheet_self_custom_view'),
    path('timesheet/overview-self/<slug:date_text>/<slug:date_range_type>/', views.timesheet_self_view,
         name='timesheet_self_custom_all_view'),

    path('timesheet/overview-class/', views.timesheet_class_view, name='timesheet_class_view'),
    path('timesheet/overview-class/<slug:date_text>/', views.timesheet_class_view, name='timesheet_class_date_view'),
    path('timesheet/overview-class/<slug:date_text>/<slug:date_range_type>/',
         views.timesheet_class_view, name='timesheet_class_date_type_view'),
    path('timesheet/overview-class/<slug:date_text>/<slug:date_range_type>/<slug:class_name_section>',
         views.timesheet_class_view, name='timesheet_class_custom_all_view'),


    path('timesheet/<slug:date_text>/<slug:profile_id>/detail', views.timesheet_detail_view,
         name='timesheet_detail_view'),


    path('reports/', views.report_view, name='report'),
    path('classes/', views.classes_view, name='classes'),
    path('settings/', views.settings_view, name='settings'),
    path('announcement/', views.announcement_view, name='announcement_view'),
    path('people/', views.people_view, name='people'),
    path('period/list/', views.period_list_view, name='period_list'),

    path('camera/list/', views.camera_list_view, name='camera_list'),

    path('staff/', views.teacher_list_view, name='teacher_list'),
    path('staff/<slug:profile_id>/', views.TeacherDetailView.as_view(), name='teacher_detail'),

    path('locations/manage/', views.location_manage_view, name='location_manage_view'),

    # form view

    path('register_user/', views.register_user_view, name='register_user_view'),
    path('register_face/', views.register_face_view, name='register_face_view'),
    # old
    path('take_attendance_class/', views.take_attendance_class_view, name='take_attendance_class_view'),
    path('take_attendance_other/', views.take_attendance_other_view, name='take_attendance_other_view'),
    # new
    path('take_attendance_self/', views.take_attendance_self_view, name='take_attendance_self_view'),
    path('take_attendance_class_preselected/', views.take_attendance_class_preselected_view,
         name='take_attendance_class_preselected'),
    path('take_attendance_cctv/', views.take_attendance_cctv_view, name='take_attendance_cctv'),

    path('take_attendance_other_preselected/', views.take_attendance_other_preselected_view,
         name='take_attendance_other_preselected'),

    path('profile/<slug:profile_id>/update/', views.profile_update_view, name='profile_update'),
    path('teacher/<slug:profile_id>/update/', views.teacher_update_view, name='teacher_update'),
    path('student/<slug:profile_id>/update/', views.student_update_view, name='student_update'),
    path('period/create/', views.period_create_view, name='period_create'),
    path('period/<slug:period_id>/update/', views.period_update_view, name='period_update'),
    path('period/<slug:period_id>/delete/', views.period_delete_view, name='period_delete'),

    path('camera/create/', views.camera_create_view, name='camera_create'),
    path('camera/<slug:camera_id>/update/', views.camera_update_view, name='camera_update'),
    path('camera/<slug:camera_id>/delete/', views.camera_delete_view, name='camera_delete'),
    path('camera/<slug:camera_id>/', views.CameraDetailView.as_view(), name='camera_detail'),

    path('announcement/create/', views.announcement_create_view, name='announcement_create'),
    path('announcement/<slug:announcement_id>/update/', views.announcement_update_view, name='announcement_update'),
    path('announcement/<slug:announcement_id>/delete/', views.announcement_delete_view, name='announcement_delete'),

    # working - change_password_v1
    path('password/', views.change_password, name='change_password'),


    # ajax view
    # path('ajax/student_register/', views.student_register_view_ajax, name='student_register_ajax'),
    path('ajax/user_register/', views.user_register_ajax, name='user_register_ajax'),
    path('ajax/role_profiles/', views.get_profiles_by_role_ajax, name='get_profiles_by_role_ajax'),
    path('ajax/get_attendance/', views.get_list_of_all_students_attendance_by_class_name_section_date_ajax,
         name='get_list_of_all_students_attendance_by_class_name_section_date_ajax'),
    path('ajax/get_attendance_status/', views.get_attendance_status_by_profile_id_ajax,
         name='get_attendance_status_by_profile_id_ajax'),

    path('ajax/camera_details/', views.get_camera_details_ajax, name='get_camera_details_ajax'),
    path('ajax/check_in_out/', views.get_check_in_out_by_profile_ajax, name='get_check_in_out_by_profile_ajax'),
    path('ajax/take_attendance/', views.take_attendance_view_ajax, name='take_attendance_ajax'),
    path('ajax/take_attendance_class/', views.take_attendance_class_view_ajax, name='take_attendance_class_view_ajax'),
    path('ajax/take_attendance_class_/', views.take_attendance_class_manual_view_ajax,
         name='take_attendance_class_manual_view_ajax'),
    path('ajax/take_attendance_self/', views.take_attendance_self_view_ajax, name='take_attendance_self_view_ajax'),
    path('ajax/take_attendance_other/', views.take_attendance_other_view_ajax, name='take_attendance_other_view_ajax'),

    path('ajax/attendance_class/', views.get_attendance_class_ajax, name='get_attendance_class_ajax'),
    path('ajax/attendance_self/', views.get_attendance_self_ajax, name='get_attendance_self_ajax'),
    path('ajax/attendance_other/', views.get_attendance_other_ajax, name='get_attendance_other_ajax'),
    path('ajax/attendance_cctv/', views.get_attendance_cctv_ajax, name='get_attendance_cctv_ajax'),

    path('ajax/load_section/', views.get_section_view_ajax, name='ajax_load_section'),
    path('ajax/report/', views.get_report_view_ajax, name='get_report_ajax'),

    # demo
    path('demo/', views.demo_view, name='demo'),

]

luein_smart_attendance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import notifications.urls
from app_root import views as root_views
from app_smart_attendance import views as app_smart_attendance_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_root.urls', namespace='root')),
    path('app/', include('app_smart_attendance.urls', namespace='app_smart_attendance')),

    # Captcha URL
    path('captcha/', include('captcha.urls'), name='captcha-image'),


    # Auth URLs
    path('login/', root_views.custom_login_view, name='login'),
    path('logout/', root_views.logout_view, name='logout'),

    # FACE RECOG APIS
    path('api/', include('api_face_recog.urls', namespace='face_recog')),


    # file manager
    path('file_manager/', include('app_file_manager.urls', namespace='app_file_manager')),

    # notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # pwa
    path('', include('pwa.urls')),

    # django-webpush
    path(r'webpush/', include('webpush.urls')),

    path('ajax/search/', app_smart_attendance_views.fetch_usernames_view_ajax, name='search'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

templates/app_smart_attendance/module/announcement/html/announcement.html
{% extends "base.html" %}

{% block title %}Home - {{block.super}}{% endblock %}

{% load static %}
{% load template_tags %}

{% block head %}
<style>{% include 'app_smart_attendance/module/announcement/css/announcement.css' %}</style>
{% endblock %}

{% block content %}
<div class="all-container">

    <div class="brdcrmb">
        <ul class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li>Announcement</li>
        </ul>
    </div>

    {% with role=request.user.profile.role %}

    {% if role == "admin" or role == "staff" or role == "school_admin" or role == "teacher" or role == "non_teacher" %}
    <div class="flx w90 ma mb10">
        <button class="button js_create_announcement pt5 pr10 pb5 pl10 mla"
                data-url="{% url 'app_smart_attendance:announcement_create' %}" data-action_type="create"
                type="button">Add
        </button>
    </div>
    {% endif %}

    <div class="announcement_list_table w90 ma" id="announcement_list_table">
        {% include 'app_smart_attendance/module/announcement/html/partial_announcement_list.html' %}
    </div>

    {% endwith %}

</div>


<!-- The Modal -->
<div class="luein-modal-container">
    <!-- Modal content -->
    <div class="luein-modal-content w80"></div>
</div>


{% endblock %}

{% block javascript %}

<script>{% include 'app_smart_attendance/module/announcement/js/announcement_list_fill_modal.js' %}</script>
<script>{% include 'app_smart_attendance/module/announcement/js/announcement.js' %}</script>
{% endblock %}

templates/app_smart_attendance/module/announcement/html/partial_announcement_create.html
<!--Modal header-->
<div class="luein-modal-header">
    <div class="luein-modal-header-text">
        Create Announcement
    </div>
    <span class="luein-modal-close">&times;</span>
</div>

<!--Modal body-->
<div class="luein-modal-body" id="luein-modal-body">
    <form method="post" action="{% url 'app_smart_attendance:announcement_create' %}" class="js_announcement_create_form" id="announcement_crud_form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="ma p10 w100">
            {% include 'app_smart_attendance/module/announcement/html/partial_announcement_form.html' %}
        </div>
    </form>
</div>
<!--Modal footer-->
<div class="luein-modal-footer">
    <button type="submit" class="luein-modal-button submit" form="announcement_crud_form">Create</button>
    <button class="luein-modal-button cancel">Cancel</button>
</div>

<script>{% include 'app_smart_attendance/module/announcement/js/announcement_list_submit.js' %}</script>
<script>{% include 'snippets/luein-modal/luein-modal-close.js' %}</script>

templates/app_smart_attendance/module/announcement/html/partial_announcement_delete.html
<!--Modal header-->
<!--<div class="luein-modal-header">-->
<!--    <div class="luein-modal-header-text">-->
<!--        Delete Question-->
<!--    </div>-->
<!--    <span class="luein-modal-close">&times;</span>-->
<!--</div>-->

<!--Modal body-->
<!--<div class="luein-modal-body">-->
<form action="{% url 'app_smart_attendance:announcement_delete' announcement_qs.announcement_id %}" class="js_announcement_delete_form" enctype="multipart/form-data" id="announcement_crud_form" method="post">
    {% csrf_token %}
    <p class="lead">Are you sure you want to delete this Announcement</p>
    <div class="flx">
        <p><span>"</span><b>{{ announcement_qs.title|safe }}</b><span>"</span></p>
    </div>
</form>
<!--</div>-->
<!--&lt;!&ndash;Modal footer&ndash;&gt;-->
<!--<div class="luein-modal-footer">-->
<!--    <button type="submit" class="luein-modal-button submit" form="announcement_crud_form">Delete</button>-->
<!--    <button class="luein-modal-button cancel">Close</button>-->
<!--</div>-->

<!--<script>{% include 'snippets/luein-modal/luein-modal-close.js' %}</script>-->

templates/app_smart_attendance/module/announcement/html/partial_announcement_form.html
{% if form.non_field_errors %}
<div class="flx non_field_errors">
    <div class="non_field_errors_div">
        {{ form.non_field_errors }}
    </div>
</div>
{% endif %}

<div class="flx flxc partitioned_form">

    <div class="partitioned_form_field">
        {{ form.title.label_tag }}
        {{ form.title }}
        {% if form.title.errors %}
        <span class="errorspan">{{ form.title.errors }}</span>
        {% endif %}
    </div>

    <div class="partitioned_form_field">
        {{ form.content.label_tag }}
        {{ form.content }}
        {% if form.content.errors %}
        <span class="errorspan">{{ form.content.errors }}</span>
        {% endif %}
    </div>

    <div class="partitioned_form_field">
            {{ form.expire_date.label_tag }}
            {{ form.expire_date }}
            {% if form.expire_date.errors %}
            <span class="errorspan">{{ form.expire_date.errors }}</span>
            {% endif %}
        </div>

    <div class="partitioned_form_field checkbox_toggle_btn_div" data-on="green" data-off="red">
        <label>{{ form.is_active.label }}:</label>
        <div class="checkbox_toggle_btn">
            {{ form.is_active }}
            <label for="{{form.is_active.auto_id}}"></label>
        </div>
        {% if form.is_active.errors %}
        <span class="errorspan">{{ form.is_active.errors }}</span>
        {% endif %}
    </div>

</div>

templates/app_smart_attendance/module/announcement/html/partial_announcement_list.html
<div class="flx flxc">
    {% if announcement_qs %}
        {% for item in announcement_qs %}
        {% if item.is_active or request.user.profile == item.created_by %}
            {% include 'app_smart_attendance/module/announcement/html/partial_announcement_card.html' %}
        {% else %}
             <div class="flx bdr p10 red">No announcements.</div>
        {% endif %}
        {% endfor %}
    {% else %}
        <div class="flx bdr p10 red">No announcements.</div>
    {% endif %}
</div>

templates/app_smart_attendance/module/announcement/html/partial_announcement_update.html
<!--Modal header-->
<div class="luein-modal-header">
    <div class="luein-modal-header-text">
        Update Announcement
    </div>
    <span class="luein-modal-close">&times;</span>
</div>

<!--Modal body-->
<div class="luein-modal-body" id="luein-modal-body">
    <form method="post"
          action="{% url 'app_smart_attendance:announcement_update' announcement_qs.announcement_id %}"
          class="js_announcement_create_form"
          id="announcement_crud_form"
          enctype="multipart/form-data">
        {% csrf_token %}
        <div class="ma p10 w100">
            {% include 'app_smart_attendance/module/announcement/html/partial_announcement_form.html' %}
        </div>
    </form>
</div>
<!--Modal footer-->
<div class="luein-modal-footer">
    <button type="submit" class="luein-modal-button submit" form="announcement_crud_form">Update</button>
    <button class="luein-modal-button cancel">Cancel</button>
</div>

<script>{% include 'app_smart_attendance/module/announcement/js/announcement_list_submit.js' %}</script>
<script>{% include 'snippets/luein-modal/luein-modal-close.js' %}</script>