app_root/urls.py
from django.urls import path, re_path

from app_root import views
from app_smart_attendance.views import SchoolDetailView, register_school_admin_view, ProfileDetailView

app_name = 'app_root'

urlpatterns = [

    # Base URLs
    path('', views.HomePageView.as_view(), name='home'),

    path('dashboard/', views.dashboard_view, name='dashboard_view'),
    path('profile/<slug:profile_id>', ProfileDetailView.as_view(), name='profile_view'),

    path('organisation/create/', views.school_create_view, name='school_create'),
    path('organisation/<slug:school_id>/', SchoolDetailView.as_view(), name='school_detail'),
    path('organisation/<slug:school_id>/update/', views.school_update_view, name='school_update'),

    path('organisation_list/', views.organisation_list_view, name='school_list'),

    path('geolocation/create/', views.geolocation_create_view, name='geolocation_create'),

    path('register_school_admin/<slug:school_id>', register_school_admin_view, name='register_school_admin_view'),


    path('ajax/validate_username/', views.validate_username_view_ajax, name='validate_username'),
    path('ajax/validate_email/', views.validate_email_view_ajax, name='validate_email'),
    # not in use - # working - change_password_v1
    path('ajax/pass-change/', views.password_change_ajax_view, name='pass-change'),

    # path('terms-conditions/', views.TermsConditionsView.as_view(), name='terms'),

    # Contact Us URLs
    # path('contact-us/', views.contact_us_view, name='contact-us'),
    # path('query-mail-sent/', views.contact_us_success_view, name='query-mail-sent'),

    # Account Activation URLs
    # path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
    #         name='activate'),
    # path('account-activated/', views.AccountActivatedView.as_view(), name='account-activated'),

    # Sitemap URL
    # path('sitemap/', views.SiteMap.as_view(), name='sitemap'),
    # path('faq/', views.faq_page_view, name='faq'),

    # check if user is alive
    # path('is_alive', views.is_alive, name='is_alive'),

]

luein_smart_attendance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import notifications.urls
from app_root import views as root_views
from app_smart_attendance import views as app_smart_attendance_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_root.urls', namespace='root')),
    path('app/', include('app_smart_attendance.urls', namespace='app_smart_attendance')),

    # Captcha URL
    path('captcha/', include('captcha.urls'), name='captcha-image'),


    # Auth URLs
    path('login/', root_views.custom_login_view, name='login'),
    path('logout/', root_views.logout_view, name='logout'),

    # FACE RECOG APIS
    path('api/', include('api_face_recog.urls', namespace='face_recog')),


    # file manager
    path('file_manager/', include('app_file_manager.urls', namespace='app_file_manager')),

    # notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # pwa
    path('', include('pwa.urls')),

    # django-webpush
    path(r'webpush/', include('webpush.urls')),

    path('ajax/search/', app_smart_attendance_views.fetch_usernames_view_ajax, name='search'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

templates/access_denied/access-denied-page.html
{% extends "base.html" %}

{% block title %}Access denied - {{block.super}}{% endblock %}

{% block content %}
{% load static %}

{% if side_nav_bar %}

<div class="all-container" id="onboard-access-denied">
    <div class="mh100vh">
        <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
            <div class="mb20 c405 t-a-c">
                <h1>Access Denied</h1>
                <img src="{% static 'website/images/error.png' %}">
            </div>

            <div class="p10"><h2>Sorry about that, but you do not have permission to access the requested page.</h2></div>
            <div class="p10">
                <div>If you require assistance, please <a class="h-t-d-n" href="#">Contact us</a></div>
            </div>
            <div class="p10">
                <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="mh100vh">
    <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
        <div class="mb20 c405 t-a-c">
            <h1>Access Denied</h1>
            <img src="{% static 'website/images/error.png' %}">
        </div>

        <div class="p10"><h2>Sorry about that, but you do not have permission to access the requested page.</h2></div>
        <div class="p10">
            <div>If you require assistance, please <a class="h-t-d-n" href="#">Contact us</a></div>
        </div>
        <div class="p10">
            <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/access_denied/access-denied.html
{% load static %}
{% if side_nav_bar %}


    <div class="all-container" id="onboard-access-denied">
    <div class="mh100vh">
        <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
            <div class="mb20 c405 t-a-c">
                <h1>Access Denied</h1>
                <img src="{% static 'website/images/error.png' %}">
            </div>

            <div class="p10"><h2>Sorry about that, but you do not have permission to access the requested page.</h2></div>
            <div class="p10">
                <div>If you require assistance, please <a class="h-t-d-n" href="#">Contact us</a></div>
            </div>
            <div class="p10">
                <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
            </div>
        </div>
    </div>
</div>
{% else %}
    <div class="mh100vh">
    <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
        <div class="mb20 c405 t-a-c">
            <h1>Access Denied</h1>
            <img src="{% static 'website/images/error.png' %}">
        </div>

        <div class="p10"><h2>Sorry about that, but you do not have permission to access the requested page.</h2></div>
        <div class="p10">
            <div>If you require assistance, please <a class="h-t-d-n" href="#">Contact us</a></div>
        </div>
        <div class="p10">
            <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
        </div>
    </div>
</div>
{% endif %}

templates/access_denied/access-denied1.html
{% extends "base.html" %}

{% block title %}Access denied - {{block.super}}{% endblock %}

{% block content %}




<div class="all-container" id="onboard-access-denied">
    {% load static %}
    <div class="mh100vh">
        <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
            <div class="mb20 c405 t-a-c">
                <h1>Access Denied</h1>
                <img src="{% static 'website/images/error.png' %}">
            </div>

            <div class="p10"><h2>Sorry about that, but you do not have permission to access the requested page.</h2></div>
            <div class="p10">First do "Onboarding" to use the platform <a class="h-t-d-n" href="#">Employer Onboarding</a></div>
            <div class="p10">
                <div>If you require assistance, please <a class="h-t-d-n" href="#">Contact us</a></div>
            </div>

            <div class="p10">
                <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/access_denied/not_for_mobile.html
{% extends "base.html" %}

{% block title %}Access denied - {{block.super}}{% endblock %}

{% block content %}
{% load static %}

{% if side_nav_bar %}
{% include 'snippets/side-nav-bar.html' %}


<div class="all-container" id="onboard-access-denied">
    <div class="mh100vh">
        <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
            <div class="mb20 c405 t-a-c">
                <h1>Info</h1>
                <img src="{% static 'images/error.png' %}">
            </div>

            <div class="p10"><h2>This window is supported in desktop version only.</h2></div>
            <div class="p10">
                <div>If you require assistance, please <a class="h-t-d-n" href="{%url 'root:contact-us'%}">Contact us</a></div>
            </div>
            <div class="p10">
                <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="mh100vh">
    <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
        <div class="mb20 c405 t-a-c">
            <h1>Info</h1>
            <img src="{% static 'images/error.png' %}">
        </div>

        <div class="p10"><h2>This window is supported in desktop version only.</h2></div>
        <div class="p10">
            <div>If you require assistance, please <a class="h-t-d-n" href="{%url 'root:contact-us'%}">Contact us</a></div>
        </div>
        <div class="p10">
            <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/access_denied/permission-denied-page.html
{% extends "base.html" %}

{% block title %}Access denied - {{block.super}}{% endblock %}

{% block content %}


{% load static %}
{% if side_nav_bar %}
{% include 'snippets/side-nav-bar.html' %}


<div class="all-container" id="onboard-access-denied">
    <div class="mh100vh">
        <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
            <div class="mb20 c405 t-a-c">
                <h1>Access Denied</h1>
                <img src="{% static 'images/error.png' %}">
            </div>

            <div class="p10"><h2>Sorry about that, but you do not have permission to access the requested page.</h2></div>
            <div class="p10"><h2>Please contact your Employer.</h2></div>
            <div class="p10">
                <div>If you require assistance, please <a class="h-t-d-n" href="{%url 'root:contact-us'%}">Contact us</a></div>
            </div>
            <div class="p10">
                <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="mh100vh">
    <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
        <div class="mb20 c405 t-a-c">
            <h1>Access Denied</h1>
            <img src="{% static 'images/error.png' %}">
        </div>

        <div class="p10"><h2>Sorry about that, but you do not have permission to access the requested page.</h2></div>
        <div class="p10"><h2>Please contact your Employer.</h2></div>

        <div class="p10">
            <div>If you require assistance, please <a class="h-t-d-n" href="{%url 'root:contact-us'%}">Contact us</a></div>
        </div>
        <div class="p10">
            <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
        </div>
    </div>
</div>
{% endif %}


{% endblock %}

templates/access_denied/permission-denied.html
{% load static %}
{% if side_nav_bar %}
{% include 'snippets/side-nav-bar.html' %}


<div class="all-container" id="onboard-access-denied">
    <div class="mh100vh">
        <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
            <div class="mb20 c405 t-a-c">
                <h1>Access Denied</h1>
                <img src="{% static 'images/error.png' %}">
            </div>

            <div class="p10"><h2>Sorry about that, but you do not have permission to access the requested page.</h2></div>
            <div class="p10"><h2>Please contact your Employer.</h2></div>
            <div class="p10">
                <div>If you require assistance, please <a class="h-t-d-n" href="{%url 'root:contact-us'%}">Contact us</a></div>
            </div>
            <div class="p10">
                <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="mh100vh">
    <div class="t-a-c p30 w90 ma mb50 bdr mt50 br5px c6">
        <div class="mb20 c405 t-a-c">
            <h1>Access Denied</h1>
            <img src="{% static 'images/error.png' %}">
        </div>

        <div class="p10"><h2>Sorry about that, but you do not have permission to access the requested page.</h2></div>
        <div class="p10"><h2>Please contact your Employer.</h2></div>

        <div class="p10">
            <div>If you require assistance, please <a class="h-t-d-n" href="{%url 'root:contact-us'%}">Contact us</a></div>
        </div>
        <div class="p10">
            <div>Go to <a class="h-t-d-n" href="{%url 'root:home'%}">Home</a></div>
        </div>
    </div>
</div>
{% endif %}