app_file_manager/urls.py
from django.urls import path, re_path
# from file_manager.folder import views
from app_file_manager import views

app_name = 'app_file_manager'


urlpatterns = [
    # folder
    path('folder/add/', views.FolderCreateView.as_view(), name='old_folder_add'),
    path('folder/', views.FolderListView.as_view(), name='old_folder_list'),
    re_path(r'^folder/delete/(?P<folder_name>[\w|\W]+)/$', views.folder_delete, name='folder_delete'),
    re_path(r'^folder/update/(?P<folder_name>[\w|\W]+)/$', views.folder_update, name='folder_update'),
    re_path(r'^folder/link/(?P<folder_name>[\w|\W]+)/$', views.folder_link, name='folder_link'),
    # re_path(r'^move/(?P<folder_name>[\w|\W]+)/$', views.folder_move, name='folder_move'),
    path('folder/add_folder/', views.folder_add_view, name='folder_add'),
    path('folder/test/', views.test_view, name='test'),



    # file
    path('file/add/', views.FileCreateView.as_view(), name='old_file_add'),
    path('file/list/', views.FileListView.as_view(), name='old_file_list'),
    path('file/<int:pk>/download/', views.FileDownloadView.as_view(), name='download'),
    re_path(r'^file/delete/(?P<file_name>[\w|\W]+)/$', views.file_delete, name='file_delete'),
    re_path(r'^file/update/(?P<file_name>[\w|\W]+)/$', views.file_update, name='file_update'),
    re_path(r'^file/link/(?P<file_name>[\w|\W]+)/$', views.file_link, name='file_link'),
    re_path(r'^file/download/(?P<file_name>[\w|\W]+)/$', views.FileDownloadNewView.as_view(), name='file_download'),
    re_path(r'^file/move/(?P<file_name>[\w|\W]+)/$', views.file_and_folder_move, name='file_move'),
    path('file/upload/', views.file_upload_view, name='file_upload'),


]

app_root/urls.py
from django.urls import path, re_path

from app_root import views
from app_smart_attendance.views import SchoolDetailView, register_school_admin_view, ProfileDetailView

app_name = 'app_root'

urlpatterns = [

    # Base URLs
    path('', views.HomePageView.as_view(), name='home'),

    path('dashboard/', views.dashboard_view, name='dashboard_view'),
    path('profile/<slug:profile_id>', ProfileDetailView.as_view(), name='profile_view'),

    path('organisation/create/', views.school_create_view, name='school_create'),
    path('organisation/<slug:school_id>/', SchoolDetailView.as_view(), name='school_detail'),
    path('organisation/<slug:school_id>/update/', views.school_update_view, name='school_update'),

    path('organisation_list/', views.organisation_list_view, name='school_list'),

    path('geolocation/create/', views.geolocation_create_view, name='geolocation_create'),

    path('register_school_admin/<slug:school_id>', register_school_admin_view, name='register_school_admin_view'),


    path('ajax/validate_username/', views.validate_username_view_ajax, name='validate_username'),
    path('ajax/validate_email/', views.validate_email_view_ajax, name='validate_email'),
    # not in use - # working - change_password_v1
    path('ajax/pass-change/', views.password_change_ajax_view, name='pass-change'),

    # path('terms-conditions/', views.TermsConditionsView.as_view(), name='terms'),

    # Contact Us URLs
    # path('contact-us/', views.contact_us_view, name='contact-us'),
    # path('query-mail-sent/', views.contact_us_success_view, name='query-mail-sent'),

    # Account Activation URLs
    # path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
    #         name='activate'),
    # path('account-activated/', views.AccountActivatedView.as_view(), name='account-activated'),

    # Sitemap URL
    # path('sitemap/', views.SiteMap.as_view(), name='sitemap'),
    # path('faq/', views.faq_page_view, name='faq'),

    # check if user is alive
    # path('is_alive', views.is_alive, name='is_alive'),

]

luein_smart_attendance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import notifications.urls
from app_root import views as root_views
from app_smart_attendance import views as app_smart_attendance_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_root.urls', namespace='root')),
    path('app/', include('app_smart_attendance.urls', namespace='app_smart_attendance')),

    # Captcha URL
    path('captcha/', include('captcha.urls'), name='captcha-image'),


    # Auth URLs
    path('login/', root_views.custom_login_view, name='login'),
    path('logout/', root_views.logout_view, name='logout'),

    # FACE RECOG APIS
    path('api/', include('api_face_recog.urls', namespace='face_recog')),


    # file manager
    path('file_manager/', include('app_file_manager.urls', namespace='app_file_manager')),

    # notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # pwa
    path('', include('pwa.urls')),

    # django-webpush
    path(r'webpush/', include('webpush.urls')),

    path('ajax/search/', app_smart_attendance_views.fetch_usernames_view_ajax, name='search'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

app_file_manager/views.py
import json
import os

from django.shortcuts import get_object_or_404, render
from wsgiref.util import FileWrapper
from django.core.files.storage import default_storage, FileSystemStorage
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic import CreateView, ListView
from django.views.generic.base import View

from app_file_manager.code_base.utils import delete_file, rename_file, move_file_or_folder, walk_dir_tree
from app_file_manager.code_base.utils import list_current_dir_tree, delete_folder, rename_folder, path_to_dict
from app_file_manager import forms
from app_file_manager.models import Folder, File
from luein_smart_attendance import settings


class FolderCreateView(CreateView):
    form_class = forms.FolderForm
    template_name = 'app_file_manager/app_folder/html/add.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_url'] = reverse('app_file_manager:old_folder_add')
        context['add_folder'] = reverse('app_file_manager:old_folder_add')
        context['add_file'] = reverse('app_file_manager:old_file_add')
        return context

    def get_success_url(self):
        return reverse('app_file_manager:old_folder_list')


class FolderListView(ListView):
    context_object_name = 'folder_list'
    template_name = 'app_file_manager/app_folder/html/list.html'

    def get_queryset(self):
        pk = self.request.GET.get('id')
        queryset = Folder.objects.all()
        if pk:
            queryset = queryset.filter(parent__pk=pk)
        else:
            queryset = queryset.filter(parent=None)

        order_by = self.request.GET.get('sort')
        if order_by == 'time':
            queryset = queryset.order_by('-created_at')
        elif order_by == 'name':
            queryset = queryset.order_by('name')

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)

        pk = self.request.GET.get('id')

        context['file_list'] = self.get_file_query(pk)
        # context['add_folder'] = reverse('folder:add')
        # context['add_file'] = reverse('file:add')

        context['add_folder'] = reverse('app_file_manager:old_folder_add')
        context['add_file'] = reverse('app_file_manager:old_file_add')

        context['parent_folder'] = self.get_parent_folder_link(pk)

        context['new_parent_folder'] = [{
            'text': 'documents',
            'link': '/?parent=' + 'documents/'
        }, {
            'text': 'child_1',
            'link': '/?parent=' + 'documents/' + 'child_1/'
        }, {
            'text': 'child_2',
            'link': '/?parent=' + 'documents/' + 'child_1/' + 'child_2/'
        }]

        parent = self.request.GET.get('parent')
        # base_path = settings.MEDIA_ROOT + "/"
        base_path = settings.BROWSE_FOLDER_ROOT

        # print('---URL parent---', parent)
        # print('---base_path---', base_path)

        if parent:
            parent_path = base_path + parent
        else:
            parent_path = base_path
            parent = ""

        tree_list = list_current_dir_tree(self.request, base_path, parent)
        context['new_list'] = tree_list
        context['new_list_for_tree'] = json.dumps(tree_list)
        context['all_folders'] = walk_dir_tree(self.request, base_path)

        context['tree_hierarchy'] = json.dumps([path_to_dict(base_path, tree_list)])

        context['parent_name'] = parent

        return context

    def get_file_query(self, pk):
        file_query = File.objects.all()
        if pk:
            file_query = file_query.filter(folder__pk=pk)
        else:
            file_query = file_query.filter(folder=None)
        order_by = self.request.GET.get('sort')
        if order_by == 'time':
            file_query = file_query.order_by('-created_at')
        elif order_by == 'name':
            file_query = file_query.order_by('name')
        return file_query

    @staticmethod
    def get_parent_folder_link(pk):
        parent_folder = []
        if pk:
            folder = Folder.objects.get(pk=pk)
            parent_folder.append({
                'text': folder.name,
                'link': reverse('app_file_manager:old_folder_list') + f'?id={folder.pk}',
            })
            while folder.parent:
                parent_folder.append({
                    'text': folder.parent.name,
                    'link': reverse('app_file_manager:old_folder_list') + f'?id={folder.parent.pk}',
                })
                folder = folder.parent
            parent_folder.reverse()
        return parent_folder

    @staticmethod
    def get_new_parent_folder_link(parent_path):
        parent_folder = []
        if pk:
            folder = Folder.objects.get(pk=pk)
            parent_folder.append({
                'text': folder.name,
                'link': reverse('app_file_manager:old_folder_list') + f'?id={folder.pk}',
            })
            while folder.parent:
                parent_folder.append({
                    'text': folder.parent.name,
                    'link': reverse('app_file_manager:old_folder_list') + f'?id={folder.parent.pk}',
                })
                folder = folder.parent
            parent_folder.reverse()
        return parent_folder


# @login_required
def folder_delete(request, **kwargs):
    # os.path.exists(path)

    parent = request.GET.get('parent')
    folder_name = kwargs.get('folder_name')
    base_path = settings.MEDIA_ROOT
    absolute_path = base_path + '/' + parent + folder_name
    dir_path = base_path + '/' + parent
    folder_path = absolute_path.replace(base_path, "")

    # print('---parent---', parent)
    # print('---folder_name---', folder_name)
    # print('---base_path---', base_path)
    # print("---absolute_path---", absolute_path)
    # print("---dir_path---", dir_path)
    # print("---folder_path---", folder_path)

    data = dict()
    if request.method == 'POST':

        # delete row from DB
        # folder_get_qs.delete()

        parent_path = dir_path
        del_msg = delete_folder(parent_path, folder_name)

        # company_users_list = create_company_users_list(request)
        # html_emp_jobs_list = create_html_emp_jobs_list(request, company_users_list)
        # data['html_emp_jobs_list'] = html_emp_jobs_list

        data['form_is_valid'] = True
        data['message'] = del_msg
    else:
        # context = {'folder_get_qs': folder_get_qs}
        context = {
            'folder': {
                'parent_name': parent,
                'folder_name': folder_name,
                'folder_path': folder_path
            }
        }
        template_name = 'app_file_manager/app_folder/html/partial_folder_delete.html'
        data['html_form'] = render_to_string(template_name=template_name, context=context, request=request)

    data['action_type'] = "delete"
    return JsonResponse(data)


def folder_update(request, **kwargs):
    template = 'app_file_manager/app_folder/html/partial_folder_update.html'

    # os.path.exists(path)
    folder_name = kwargs.get('folder_name')
    print('---folder_name---', folder_name)

    parent = request.GET.get('parent')
    base_path = settings.MEDIA_ROOT
    absolute_path = base_path + '/' + parent
    dir_path = base_path + '/' + parent
    folder_path = absolute_path.replace(base_path, "")

    print('---parent---', parent)
    print('---base_path---', base_path)
    print("---absolute_path---", absolute_path)
    print("---dir_path---", dir_path)
    print("---folder_path---", folder_path)

    data = dict()
    if request.method == 'POST':
        folder_rename_form = forms.FolderRenameForm(data=request.POST, folder_name=folder_name)
        if folder_rename_form.is_valid():
            # delete row from DB
            # folder_get_qs.delete()

            parent_path = dir_path
            old_name = folder_name
            new_name = folder_rename_form.cleaned_data['new_name']
            print('---new_name---', new_name)

            del_msg = rename_folder(parent_path, old_name, new_name)

            # company_users_list = create_company_users_list(request)
            # html_emp_jobs_list = create_html_emp_jobs_list(request, company_users_list)
            # data['html_emp_jobs_list'] = html_emp_jobs_list

            data['form_is_valid'] = True
            data['message'] = del_msg
        else:
            data['form_is_valid'] = False
            data['message'] = "failed"
    else:
        # context = {'folder_get_qs': folder_get_qs}
        folder_rename_form = forms.FolderRenameForm(folder_name=folder_name)

        context = {
            'folder': folder_name,
            "parent_name": parent,
            "form": folder_rename_form
        }
        data['html_form'] = render_to_string(template_name=template, context=context, request=request)

    data['action_type'] = "update"
    return JsonResponse(data)


def folder_link(request, **kwargs):
    template = 'app_file_manager/app_folder/html/partial_folder_update.html'

    # os.path.exists(path)
    folder_name = kwargs.get('folder_name')
    print('---folder_name---', folder_name)

    parent = request.GET.get('parent')
    base_path = settings.MEDIA_ROOT
    absolute_path = base_path + parent
    dir_path = base_path + parent
    folder_path = absolute_path.replace(base_path, "")

    # print('---parent---', parent)
    # print('---base_path---', base_path)
    # print("---absolute_path---", absolute_path)
    # print("---dir_path---", dir_path)
    # print("---folder_path---", folder_path)

    data = dict()
    if request.method == 'POST':
        folder_rename_form = forms.FolderRenameForm(data=request.POST, folder_name=folder_name)
        if folder_rename_form.is_valid():
            # delete row from DB

templates/app_file_manager/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="author" content="nahidsaikat">
    <meta name="description" content="Link Manager">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="/fontawesome/css/all.css">
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/styles/style.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <!--    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>-->
    <script src="/fontawesome/js/solid.js"></script>


    <link rel="stylesheet" href="/luein_css/normalise.css">
    <link rel="stylesheet" href="/luein_css/employer.css">
    <link rel="stylesheet" href="/luein_modal/luein-modal.css">
    <link rel="stylesheet" href="/dynamic_loader/dynamic-loader.css">
    <link rel="stylesheet" href="/dynamic-confirmation/dynamic-confirmation.css">
    <link rel="stylesheet" href="/alerts/alert.css">

    {% block css %}{% endblock %}

    <title>Link Manager</title>
</head>
<body>

<div class="wrapper ">
    <div id="alert-div"></div>
        <nav class="sidebar">
            {{tree_hierarchy}}
        </nav>
    <!-- Sidebar -->
    <nav class="dn" id="sidebar">
        <div class="text-center brand">
            <a class="large-font text-white" href="/">
                File Manager
            </a>
        </div>
        <hr/>

        <ul class="list-unstyled components text-white">
            <li class="">
                <a class="text-white" href="/">Home</a>
            </li>

            <li class="">
                <a class="text-white" href="{{ add_folder }}">
                    <i class="fas fa-folder-plus mr15 lightgray"></i>Add Folder</a>
            </li>

            <li class="">
                <a class="text-white" href="{{ add_file }}">
                    <i class="fas fa-file-upload ml-1 mr15 lightgray"></i>File Upload</a>
            </li>


            <li class="">
                <a class="text-white" href="{{ upload_folder }}">
                    <i class="fas fa-folder-plus mr15 lightgray"></i>Folder Upload</a>
            </li>

        </ul>
        <div class="text-center bottom mb55">
            <span>Sort by</span>
            <a class="text-white" id="time_sort" href="/">
                time</a>
            |
            <a class="text-white" id="name_sort" href="/">
                name</a>
        </div>
    </nav>
    <!-- Page Content -->
    <div id="content" class="w100">
        <div class="ml290 mb60">

            <!-- Breadcrumb -->
            <div class="container ml20 mt-3 dn">
                {% if parent_folder %}
                    <a href="/"><span class="text-info">Home</span></a>
                    <span class="mlr2 text-info">/</span>
                    {% for link in parent_folder %}
                        {% if not forloop.last %}
                            <a href="{{ link.link }}"><span class="text-info">{{ link.text }}</span></a>
                            <span class="mlr2 text-info">/</span>
                        {% else %}
                            <span class="">{{ link.text }}</span>
                        {% endif %}
                    {% endfor %}

                {% endif %}
            </div>

            <!-- Breadcrumb -->
            <div class="container ml20 mt-3 ">
                {% if new_list.breadcrumb_list %}
                <a href="/"><span class="text-info">Home</span></a>
                <span class="mlr2 text-info">/</span>
                {% for link in new_list.breadcrumb_list %}
                {% if not forloop.last %}
                <a href="{{ link.link }}"><span class="text-info">{{ link.text }}</span></a>
                <span class="mlr2 text-info">/</span>
                {% else %}
                <span class="">{{ link.text }}</span>
                {% endif %}
                {% endfor %}
                {% else %}
                    <a href="/"><span class="text-info">Home</span></a>
                {% endif %}
            </div>

            <div class="flx w100">
                <div class="flx mla">



                    <div class="action_container">
                        <div class="action_btn add js_add_folder cp flx" data-action_type="add"
                             data-url="{% url 'app_file_manager:folder_add' %}?parent={{parent_name}}" title="Add">
                            <div class="folder-add-fafa-div flx mr10">
                                <svg class="m5" width="16" height="16" aria-hidden="true" focusable="false" data-prefix="fas"
                             data-icon="folder-plus" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"
                             data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M464 128H272l-64-64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V176c0-26.51-21.49-48-48-48zm-96 168c0 8.84-7.16 16-16 16h-72v72c0 8.84-7.16 16-16 16h-16c-8.84 0-16-7.16-16-16v-72h-72c-8.84 0-16-7.16-16-16v-16c0-8.84 7.16-16 16-16h72v-72c0-8.84 7.16-16 16-16h16c8.84 0 16 7.16 16 16v72h72c8.84 0 16 7.16 16 16v16z"></path>
                        </svg>
                            </div>
                            <div class="flx">Add folder</div>
                        </div>
                    </div>

                    <div class="action_container">
                        <div class="action_btn upload js_upload_file cp flx" data-action_type="upload"
                             data-url="{% url 'app_file_manager:file_upload' %}?parent={{parent_name}}" title="Upload">
                            <div class="file-upload-fafa-div flx mr10">
                                <svg class="m5" width="16" height="16" aria-hidden="true" focusable="false" data-prefix="fas"
                             data-icon="file-upload" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"
                             data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M224 136V0H24C10.7 0 0 10.7 0 24v464c0 13.3 10.7 24 24 24h336c13.3 0 24-10.7 24-24V160H248c-13.2 0-24-10.8-24-24zm65.18 216.01H224v80c0 8.84-7.16 16-16 16h-32c-8.84 0-16-7.16-16-16v-80H94.82c-14.28 0-21.41-17.29-11.27-27.36l96.42-95.7c6.65-6.61 17.39-6.61 24.04 0l96.42 95.7c10.15 10.07 3.03 27.36-11.25 27.36zM377 105L279.1 7c-4.5-4.5-10.6-7-17-7H256v128h128v-6.1c0-6.3-2.5-12.4-7-16.9z"></path>
                        </svg>
                            </div>
                            <div class="flx">File upload</div>
                        </div>
                    </div>


                </div>
            </div>

            {% block content %}
            {% endblock %}
        </div>
    </div>


    <!-- The Modal -->
    <div class="luein-modal-container">
        <!-- Modal content -->
        <div class="luein-modal-content w80"></div>
    </div>
</div>

<footer class="page-footer font-small green fixed-bottom text-white dn">
    <div class="footer-copyright text-center py-3 mr-3"> © 2022 Copyright:
        <a href="#"> Luein Analytics</a>
    </div>
</footer>

<!--<script src="/jquery/js/jquery.min.js"></script>-->
<script src="/jquery/js/jquery-3.6.1.js"></script>
<script src="/jquery/js/popper.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/fontawesome/js/all.js"></script>


<!-- Popper.JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<!-- jQuery Custom Scroller CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>


<script>
      $(document).ready(function () {
        $("#sidebar").mCustomScrollbar({
             theme: "minimal"
        });
      });

      $("#time_sort").click(function(event){
          event.preventDefault();
          var main_url = window.location.href;
          var split_url = main_url.split('&'), url;

          if (split_url[0].includes('?')){
              url = split_url[0] + '&sort=time';
          }
          else{
              url = split_url[0] + '?sort=time';
          }

          window.location.replace(url);
      });

      $("#name_sort").click(function(event){
          event.preventDefault();
          var main_url = window.location.href;
          var split_url = main_url.split('&'), url;

          if (split_url[0].includes('?')){
              url = split_url[0] + '&sort=name';
          }
          else{
              url = split_url[0] + '?sort=name';
          }

          window.location.replace(url);

      });
</script>

<script src="/dynamic_loader/dynamic-loader.js"></script>
<script src="/dynamic-confirmation/dynamic-confirmation.js"></script>
<script src="/alerts/alert.js"></script>
<script src="/luein_modal/luein-modal-functions.js"></script>


<script>{% include 'base.js' %}</script>

{% block js %}{% endblock %}
</body>
</html>

templates/app_file_manager/test.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<style type="text/css">
body
{
    font-family: Arial;
    font-size: 10pt;
}
img
{
    height: 100px;
    width: 100px;
    margin: 2px;
}
.draggable
{
    filter: alpha(opacity=60);
    opacity: 0.6;
}
.dropped
{
    position: static !important;
}
#dvSource, #dvDest
{
    border: 5px solid #ccc;
    padding: 5px;
    min-height: 100px;
    width: 430px;
}
</style>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.8.24/jquery-ui.min.js" type="text/javascript"></script>
<link href="http://code.jquery.com/ui/1.8.24/themes/blitzer/jquery-ui.css" rel="stylesheet"
type="text/css" />

</head>
<body>
<div id="dvSource">
        {% load static %}

    <img alt="" src="{% static 'media/img/test.png' %}" />
</div>
<hr />
<div id="dvDest">
    Drop here
</div>

<script type="text/javascript">
$(function () {
    $("#dvSource img").draggable({
        revert: "invalid",
        refreshPositions: true,
        drag: function (event, ui) {
            ui.helper.addClass("draggable");
        },
        stop: function (event, ui) {
            ui.helper.removeClass("draggable");
            var image = this.src.split("/")[this.src.split("/").length - 1];
            if ($.ui.ddmanager.drop(ui.helper.data("draggable"), event)) {
                alert(image + " dropped.");
            }
            else {
                alert(image + " not dropped.");
            }
        }
    });
    $("#dvDest").droppable({
        drop: function (event, ui) {
            if ($("#dvDest img").length == 0) {
                $("#dvDest").html("");
            }
            ui.draggable.addClass("dropped");
            $("#dvDest").append(ui.draggable);
        }
    });
});
</script>
</body>
</html>